### ISSUE TITLE
Speed hook not working?

### ISSUE THREAD

**Issue by archerdom** [ermaccer/MKXHook#2]
The game speed hook doesn't seem to work, although the individual character speed hooks do?

**Comment by ermaccer** [comment]
You need to specify for how long the speed change should work (ticks box).

**Comment by archerdom** [comment]
Oh, so that's what that was. Why does it go negative then? And can you make an infinite version?

**Comment by archerdom** [comment]
I love it! Is it possible to make this for MK11, or does the anti-cheat block it?

**Comment by ermaccer** [comment]
The only thing that blocks me from doing MK11Hook is maintenance, MK11 is constantly updated and it would be pain to update it (plus exe size is around 500mb, so would take even more time to reanalyze it).

I have done some work for Injustice 2 (if that interests you): https://github.com/ermaccer/I2Hook

**Comment by archerdom** [comment]
Understandable. Probably once they stop updating it, then! I'll take a look at the Injustice one.
