### ISSUE TITLE
Hi,ermaccer.

### ISSUE THREAD

**Issue by Thekingdom-CHS** [ermaccer/MKXHook#3]
Hi, Ermaccer:
    I'm trying to translate this game into another language.
    But, this game has a hash check, So, If I edit text file, This game will not launch.
    Luckly, I find "MKXHook", Game can playing now. But, game seems can't connect with Online Mode.
    I notice this in your update log:
    `Added a disclaimer about asset hash disable and online (you can't access most of features when it is active, every other option does not affect online gameplay).`
    Will this mean, its you block online mode? Or just the original program logic?
    I'm sorry to bother you, But this is important to me.

   Best regards,
   Thekingdom

**Comment by thethiny** [comment]
I think I need to discuss with @ermaccer on an alternate online-proof method. Let me see what I can do about this.

**Comment by Thekingdom-CHS** [comment]
> I think I need to discuss with @ermaccer on an alternate online-proof method. Let me see what I can do about this.



Thanks for your reply. I'm sorry for replying to you so late. I was busy with my interview, so I didn't check the message in time.

If can‘t issue this, It's will be ok.

I didn't expect you reply me after sending this subject. 

There are not as many people playing the game as before.

I even don't know how many people will use my translation.
