### ISSUE TITLE
Way to Bypass some MKXHOOK errors?

### ISSUE THREAD

**Issue by AlinResources** [ermaccer/MKXHook#4]
Hi i had downloaded all MKXhook versions and it refuse to run all versions maybe it says Unable  to Load MKXHOOK.asi so i dont know other alternative to add modifiers and fatality on npc so what i should do?
P.S. I don't reinstall the MKX since i have modded costumes

**Comment by ermaccer** [comment]
The only supported version is latest Steam, I do not plan to support any other versions.
If you update to Steam and it still fails to launch, perhaps a redist is missing?

**Comment by AlinResources** [comment]
Probably , so if i want to recreate the MKXHOOK.asi what programs for compiling i need to use?

**Comment by AlinResources** [comment]
> The only supported version is latest Steam, I do not plan to support any other versions.
> If you update to Steam and it still fails to launch, perhaps a redist is missing?

What about to build a MKXHook for my private version of my mkx i try to perform corrupted shinnok fatality on baraka an example

**Comment by ermaccer** [comment]
> 
> 
> Probably , so if i want to recreate the MKXHOOK.asi what programs for compiling i need to use?

You can use any debugger to find required addresses and change them in the code.


> 
> 
> > The only supported version is latest Steam, I do not plan to support any other versions.
> > If you update to Steam and it still fails to launch, perhaps a redist is missing?
> 
> What about to build a MKXHook for my private version of my mkx i try to perform corrupted shinnok fatality on baraka an example

Like I said, I will only support latest Steam release.

**Comment by AlinResources** [comment]
ollydbg not supported so what debuggers are supporting this executable , as i know also where did manage the mkx  version in Menu or credits?

**Comment by ermaccer** [comment]
> 
> 
> ollydbg not supported so what debuggers are supporting this executable , as i know also where did manage the mkx version in Menu or credits?

You can try x64dbg. What do you mean with the second question?

**Comment by AlinResources** [comment]
i mean how to get the version  of MKX? i try x64 dbg so i can edit the exe to allow NPC fatality vs NPC is the single thing i need to know.I understand your plan so i had more in my own edition of MKX
Here i added the skins to mkx
![Screenshot (569)](https://user-images.githubusercontent.com/25686544/111077043-ab42c380-84f7-11eb-8cf3-853b24c9eca2.png)
![Screenshot (641)](https://user-images.githubusercontent.com/25686544/111077056-be559380-84f7-11eb-8c16-3a0704547366.png)

Does the Coalesced.ini and .eng and the X64TOC.txt are same files in the steam version and other versions?I don't get it.

**Comment by thethiny** [comment]
Yes the coalesced.ibi and .eng and x64TOC are the same in all versions.
