### ISSUE TITLE
Still functioning ?

### ISSUE THREAD

**Issue by Luna-Blacklight** [ermaccer/MKXHook#7]
Is this still working ? I have the latest version of MK XL but pressing F1 in-game triggers nothing. I put the contents of the zipped archive in game's Retail folder as instructed.

**Comment by ermaccer** [comment]
I assume you get the console window but no menu? This is an issue some people are experiencing that I have no idea how to fix - it might be something broken in Windows or some overlay application is causing a conflict (FRAPS does, MSI Afterburner/RTSS is fine).

**Comment by Luna-Blacklight** [comment]
Well, no. I don't get the console menu either. The only overlay I have is Nvidia

**Comment by RevenantNikhil** [comment]
In my case everything is showing bt why the hell isn't working....😥
